[security_compliance]
password_regex = ^[!-~]{8,}\Z
password_regex_description = Use at least 8 printable ASCII characters without spaces.
change_password_upon_first_use = true
unique_last_password_count = 1
minimum_password_age = 0
lockout_failure_attempts = 4
lockout_duration = 900
