[deployment]
deployment-0 ansible_host=10.0.0.1
[control]
control-06 ansible_host=10.0.0.150
control-07 ansible_host=10.0.0.151
control-08 ansible_host=10.0.0.152
[network]
control-06 ansible_host=10.0.0.150
control-07 ansible_host=10.0.0.151
control-08 ansible_host=10.0.0.152
[compute]
compute-02 ansible_host=10.0.0.146
compute-03 ansible_host=10.0.0.147
[storage]
control-06 ansible_host=10.0.0.150
control-07 ansible_host=10.0.0.151
control-08 ansible_host=10.0.0.152
[monitoring]
control-06 ansible_host=10.0.0.150
control-07 ansible_host=10.0.0.151
control-08 ansible_host=10.0.0.152
compute-02 ansible_host=10.0.0.146
compute-03 ansible_host=10.0.0.147
