[deployment]
deployment-0 ansible_host=host-deployment.local
[control]
control-06 ansible_host=host-control-06.local
control-07 ansible_host=host-control-07.local
control-08 ansible_host=host-control-08.local
[network]
control-06 ansible_host=host-control-06.local
control-07 ansible_host=host-control-07.local
control-08 ansible_host=host-control-08.local
[compute]
compute-02 ansible_host=host-compute-02.local
compute-03 ansible_host=host-compute-03.local
[storage]
control-06 ansible_host=host-control-06.local
control-07 ansible_host=host-control-07.local
control-08 ansible_host=host-control-08.local
[monitoring]
control-06 ansible_host=host-control-06.local
control-07 ansible_host=host-control-07.local
control-08 ansible_host=host-control-08.local
compute-02 ansible_host=host-compute-02.local
compute-03 ansible_host=host-compute-03.local
