[DEFAULT]
enabled_hardware_types = ipmi,redfish
enabled_power_interfaces = ipmitool,redfish
enabled_management_interfaces = ipmitool,redfish

enabled_boot_interfaces = pxe
default_boot_interface = pxe
enabled_deploy_interfaces = direct
default_deploy_interface = direct

enabled_inspect_interfaces = no-inspect
default_inspect_interface = no-inspect
enabled_network_interfaces = noop
default_network_interface = noop
enabled_storage_interfaces = noop
default_storage_interface = noop
enabled_raid_interfaces = no-raid
default_raid_interface = no-raid
enabled_bios_interfaces = no-bios
default_bios_interface = no-bios
enabled_console_interfaces = no-console
default_console_interface = no-console
enabled_rescue_interfaces = no-rescue
default_rescue_interface = no-rescue
enabled_firmware_interfaces = no-firmware
default_firmware_interface = no-firmware
enabled_vendor_interfaces = no-vendor
default_vendor_interface = no-vendor

redfish_verify_ca = False

[conductor]
automated_clean = false
sync_power_state_interval = 60
power_state_change_timeout = 60
heartbeat_interval = 10
heartbeat_timeout = 60
